### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'eglGetCurrentContext'

### ISSUE THREAD

**Issue by ChengBo5** [mks0601/Hand4Whole_RELEASE#11]
Hello, I run the demo according to the README file you gave, but the following error occurred:：
```
(torch1.8) chengbo@DESKTOP-7CQ3A90:~/code/Hand4Whole_RELEASE/demo$ python demo.py 
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    from utils.vis import render_mesh, save_obj
  File "/home/chengbo/code/Hand4Whole_RELEASE/main/../common/utils/vis.py", line 9, in <module>
    import pyrender
  File "/home/chengbo/anaconda3/envs/torch1.8/lib/python3.8/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/home/chengbo/anaconda3/envs/torch1.8/lib/python3.8/site-packages/pyrender/light.py", line 10, in <module>
    from OpenGL.GL import *
  File "/home/chengbo/code/pyopengl/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/chengbo/code/pyopengl/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/chengbo/code/pyopengl/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/chengbo/code/pyopengl/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
  File "src/errorchecker.pyx", line 19, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__
  File "/home/chengbo/code/pyopengl/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/chengbo/code/pyopengl/OpenGL/platform/baseplatform.py", line 355, in CurrentContextIsValid
    return self.GetCurrentContext
  File "/home/chengbo/code/pyopengl/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/chengbo/code/pyopengl/OpenGL/platform/egl.py", line 102, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
AttributeError: 'NoneType' object has no attribute 'eglGetCurrentContext'
```

this is my environment：
PyOpenGL            3.1.0 
PyOpenGL-accelerate 3.1.3b2 
pyrender            0.1.45
torch               1.8.0
torchaudio          0.8.0a0+a751e1d
torchgeometry       0.1.2
torchvision         0.9.0

Have you ever encountered it and how to solve it?

**Comment by mks0601** [comment]
Maybe you're trying the codes on a machine that does not have display output device?

**Comment by ChengBo5** [comment]
Yes, I use the ubuntu environment to install WSL2 on win10. I have solved this problem now.

Remove the code in vis.py.
`#os.environ["PYOPENGL_PLATFORM"] = "egl"`

and install the following driver packages.
```
sudo apt-get install freeglut3-dev
sudo apt install freeglut3-dev freeglut3 libgl1-mesa-dev libglu1-mesa-dev libxext-dev libxt-dev
sudo apt install python3-opengl libgl1-mesa-glx libglu1-mesa
```

谢谢老哥的快速的回复。
