### ISSUE TITLE
I have googled it, but it has not been solved yet. I have the following problem, please help me

### ISSUE THREAD

**Issue by siqi0905** [mks0601/Hand4Whole_RELEASE#61]
I only used MSCOCO for train.
Trying the 1st: 1st: pre-train Hand4Whole and run
 `python train.py --gpu 0-3 --lr 1e-4 --continue`
Getting the following error

`Traceback (most recent call last):
  File "train.py", line 82, in <module>
    main()
  File "train.py", line 53, in main
    loss = trainer.model(inputs, targets, meta_info, 'train')
  File "/home/wansiqi1/.custom/pyrender78/envs/train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wansiqi1/.custom/pyrender78/envs/train/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/wansiqi1/.custom/pyrender78/envs/train/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wansiqi1/.custom/pyrender78/envs/train/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/wansiqi1/.custom/pyrender78/envs/train/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
KeyError: Caught KeyError in replica 0 on device 0.`

Anyone else seen this? Thanks!

**Comment by mks0601** [comment]
what is pyrender78?

**Comment by siqi0905** [comment]
It is the name I used to customize the image on the cloud server.
I find that I get no error when I use dataset Human36M+MSCOCO+MPII, but I get this error when I use only one of them.

**Comment by mks0601** [comment]
How do you set trainset_3d and trainset_2d in config.py?

**Comment by siqi0905** [comment]
`trainset_3d = []`
`trainset_2d = ['MSCOCO'] `

**Comment by mks0601** [comment]
<img width="1512" alt="Screenshot 2023-02-04 at 12 47 57 AM" src="https://user-images.githubusercontent.com/13601723/216751249-e16eb6f0-f1f4-4600-88f0-a4e1841c1b68.png">

I have just downloaded current repo and ran without any problem.

**Comment by Julylala** [comment]
> `trainset_3d = []` `trainset_2d = ['MSCOCO'] `



> It is the name I used to customize the image on the cloud server. I find that I get no error when I use dataset Human36M+MSCOCO+MPII, but I get this error when I use only one of them.

Hello, do you know what's causing this problem
